# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros
%define keepstatic 1

Name:       tinycdb
Summary:    Constant Database manipulation library
Version:    0.77
Release:    1
Group:      System/Libraries
License:    Public Domain
URL:        http://www.corpit.ru/mjt/tinycdb.html
Source0:    http://www.corpit.ru/mjt/%{name}/%{name}_%{version}.tar.gz
Source100:  tinycdb.yaml
Patch0:     fix-build-prefix.patch
Patch1:     cflags.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(glib-2.0)


%description
tinycdb is a small, fast and reliable utility and subroutine library for 
creating and reading constant databases. The database structure is tuned
for fast reading.

This package contains tinycdb utility and shared library.



%package devel
Summary:    Development files for tinycdb
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development and headers for tinycdb



%prep
%setup -q -n %{name}-%{version}

# fix-build-prefix.patch
%patch0 -p1
# cflags.patch
%patch1 -p1
# >> setup
sed -i -e 's\/lib\/%{_lib}\g' debian/libcdb.pc
# << setup

%build
# >> build pre
# << build pre



# >> build post
%makeinstall install-sharedlib \
INSTALLPROG=cdb-shared CP="cp -p"
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
make DESTDIR=%{buildroot} install-all install-nss install-piclib install-sharedlib
chmod +x %{buildroot}%{_libdir}/*.so.*
#rm -f %{buildroot}%{_libdir}/lib*.a
mkdir -p %{buildroot}%{_libdir}/pkgconfig
cp -p debian/libcdb.pc %{buildroot}%{_libdir}/pkgconfig/libcdb.pc
file %{buildroot}/usr/lib/libcdb.so.1
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/cdb
/usr/lib/libnss_cdb.so.2
/usr/lib/libcdb.so.1
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/cdb.h
/usr/lib/libcdb.a
%config(noreplace) /etc/cdb-Makefile
%{_libdir}/libcdb.so
%{_libdir}/libcdb_pic.a
%{_libdir}/libcdb*.a
%{_libdir}/pkgconfig/*.pc
%doc %{_mandir}/man*/cdb*
# << files devel

